[project]
name = "server-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rich>=14.2.0",
    "tomli-w>=1.2.0",
    "tomli>=2.0.1",
]
